CREATE DATABASE JOINS2;
USE JOINS2;

CREATE TABLE CLIENTE (
IDCLIENTE INT PRIMARY KEY auto_increment,
NOME VARCHAR(30) NOT NULL,
SEXO ENUM ('M', 'F') NOT NULL,
EMAIL VARCHAR(50) UNIQUE,
CPF VARCHAR (15) UNIQUE);

INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF)
VALUES
('Joao', 'M', 'joao@bol.com', '76984352456'),
('Carla', 'F', 'carla@bol.com', '76984356699'),
('Ana', 'F', 'ana@bol.com', '76984357755'),
('Clara', 'F', 'clara@bol.com', '76984353344'),
('Jorge', 'M', 'jorge@bol.com', '76984352211'),
('Celia', 'F', 'celia@bol.com', '76984359988');


SELECT * FROM CLIENTE;

CREATE TABLE ENDERECO (
IDENDERECO INT PRIMARY KEY auto_increment,
RUA VARCHAR(30) NOT NULL,
BAIRRO VARCHAR(30) NOT NULL,
CIDADE VARCHAR(30) NOT NULL,
ESTADO VARCHAR(2) NOT NULL,
ID_CLIENTE INT UNIQUE,
foreign key (ID_CLIENTE) REFERENCES cliente(IDCLIENTE));

SELECT * FROM ENDERECO;

INSERT INTO ENDERECO (RUA, BAIRRO, CIDADE, ESTADO, ID_CLIENTE)
VALUES
('Rua Antonio SA', 'Centro', 'B. Horizonte', 'MG', 4),
('Rua Capitao Hermes', 'Centro', 'Rio de Janeiro', 'RJ', 1),
('Rua Pres Vargas', 'Jardins', 'Sao Paulo', 'SP', 3),
('Rua Alfandega', 'Estacio', 'Rio de Janeiro', 'RJ', 2),
('Rua do Ouvidor', 'Flamengo', 'Rio de Janeiro', 'RJ', 6),
('Rua Uruguaiana', 'Centro', 'Vitoria', 'ES', 5);

CREATE TABLE TELEFONE (
IDTELEFONE INT PRIMARY KEY auto_increment,
TIPO ENUM ('RES', 'COM', 'CEL') NOT NULL,
NUMERO VARCHAR(10) NOT NULL,
ID_CLIENTE INT,
foreign key (ID_CLIENTE) REFERENCES cliente(IDCLIENTE));

INSERT INTO TELEFONE (TIPO, NUMERO, ID_CLIENTE)
VALUES
('cel', '78458743', 5),
('res', '56576876', 5),
('cel', '87666898', 1),
('com', '54768899', 2),
('res', '78989765', 1),
('cel', '99766676', 3),
('cel', '78458743', 3),
('com', '66687899', 1),
('res', '89986668', 5),
('cel', '88687909', 2);

SELECT * FROM TELEFONE;

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE FROM CLIENTE
JOIN ENDERECO ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
WHERE CLIENTE.SEXO = 'F'
GROUP BY CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE;

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO FROM CLIENTE
JOIN ENDERECO ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
JOIN TELEFONE ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
ORDER BY NOME;

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.CIDADE, TELEFONE.NUMERO FROM cliente
JOIN ENDERECO ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
JOIN TELEFONE ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
WHERE SEXO = 'M'
ORDER BY CLIENTE.NOME;

SELECT CLIENTE.IDcliente, CLIENTE.EMAIL, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.NUMERO FROM cliente
JOIN ENDERECO ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
JOIN TELEFONE ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE
WHERE CIDADE = 'Rio de Janeiro' and bairro = "centro"
ORDER BY TELEFONE.NUMERO;

desc cliente;
desc telefone;
desc endereco;

CREATE VIEW V_RELATORIO AS
SELECT C.NOME, C.SEXO, C.EMAIL, T.TIPO, T.NUMERO, E.BAIRRO, E.CIDADE, E.ESTADO FROM CLIENTE C
JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE;

SELECT * FROM V_RELATORIO;

SHOW DATABASES;

SELECT NOME, NUMERO, ESTADO FROM V_RELATORIO;

DELETE FROM V_RELATORIO
WHERE NOME = Jorge;

INSERT INTO V_RELATORIO
values
("Cida", "F", "cida@bol.com", "Cel", "77994457", "Centro", "Vitoria", "ES");

INSERT INTO V_RELATORIO(NOME, SEXO, EMAIL, TIPO, NUMERO, BAIRRO, CIDADE, ESTADO)
values
("Cida", "F", "cida@bol.com", "Cel", "77994457", "Centro", "Vitoria", "ES");

UPDATE V_RELATORIO
SET NOME = "Jose"
WHERE NOME = "Jorge";

SELECT * FROM V_RELATORIO
WHERE SEXO = "F"
ORDER BY "NOME";

ALTER TABLE CLIENTE
ADD COLUMN DATA_ULT_COMPRA DATE;

UPDATE CLIENTE SET DATA_ULT_COMPRA = "2024-08-01" WHERE IDCLIENTE= "1";
UPDATE CLIENTE SET DATA_ULT_COMPRA = "2024-08-02" WHERE IDCLIENTE= "2";
UPDATE CLIENTE SET DATA_ULT_COMPRA = "2024-08-03" WHERE IDCLIENTE= "3";
UPDATE CLIENTE SET DATA_ULT_COMPRA = "2024-08-04" WHERE IDCLIENTE= "4";
UPDATE CLIENTE SET DATA_ULT_COMPRA = "2024-08-05" WHERE IDCLIENTE= "5";
UPDATE CLIENTE SET DATA_ULT_COMPRA = "2024-08-06" WHERE IDCLIENTE= "6";

SELECT * FROM CLIENTE;

ALTER TABLE CLIENTE
ADD COLUMN VALOR_COMPRA DECIMAL;

UPDATE CLIENTE SET VALOR_COMPRA = "1000" WHERE IDCLIENTE= "1";
UPDATE CLIENTE SET VALOR_COMPRA = "2000" WHERE IDCLIENTE= "2";
UPDATE CLIENTE SET VALOR_COMPRA = "3000" WHERE IDCLIENTE= "3";
UPDATE CLIENTE SET VALOR_COMPRA = "4000" WHERE IDCLIENTE= "4";
UPDATE CLIENTE SET VALOR_COMPRA = "5000" WHERE IDCLIENTE= "5";
UPDATE CLIENTE SET VALOR_COMPRA = "6000" WHERE IDCLIENTE= "6";

ALTER VIEW V_RELATORIO AS
SELECT C.DATA_ULT_COMPRA, C.NOME, C.SEXO, C.EMAIL, T.TIPO, T.NUMERO, E.BAIRRO, E.CIDADE, E.ESTADO, C.VALOR_COMPRA FROM CLIENTE C
JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE;

CREATE VIEW V_CompraAcima3000 AS
SELECT C.DATA_ULT_COMPRA, C.NOME, C.SEXO, C.EMAIL, T.TIPO, T.NUMERO, E.BAIRRO, E.CIDADE, E.ESTADO, C.VALOR_COMPRA FROM CLIENTE C
JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE VALOR_COMPRA >= 3000;

SELECT * FROM V_COMPRAACIMA3000;

DROP VIEW V_COMPRATOTAL;
#1 Crie uma View para mostrar o valor total das compras efetuadas pelos clientes.
CREATE VIEW V_CompraTotal AS
SELECT SUM(C.VALOR_COMPRA) AS TOTAL_COMPRAS
FROM CLIENTE C;

SELECT * FROM V_COMPRAtotal;

#2 Crie uma View para mostrar o menor valor de compras efetuadas pelos clientes.
CREATE VIEW V_CompraMin AS
SELECT MIN(C.VALOR_COMPRA) AS MINIMO_COMPRA
FROM CLIENTE C;

SELECT * FROM V_COMPRAMIN;

#3 Crie uma View para mostrar a média do valor de compras efetuadas pelos clientes.
CREATE VIEW V_CompraMedia AS
SELECT AVG(C.VALOR_COMPRA) AS MEDIA_COMPRA
FROM CLIENTE C;

SELECT * FROM V_COMPRAMEDIA;

#4 Crie uma View para mostrar o maior valor de compras efetuadas pelos clientes. 
CREATE VIEW V_CompraMax AS
SELECT MAX(C.VALOR_COMPRA) AS MAXIMA_COMPRA
FROM CLIENTE C;

SELECT * FROM V_COMPRAMAX;

DROP VIEW V_COMPRAMAXCLIENTE;
#5 Crie uma View para mostrar o maior valor de compras efetuadas pelos clientes e o nome do cliente.
CREATE VIEW V_CompraMaxCliente AS
SELECT C.IDCLIENTE, C.NOME, C.VALOR_COMPRA AS MAIOR_COMPRA
FROM CLIENTE C
WHERE C.VALOR_COMPRA = (SELECT MAX(C.VALOR_COMPRA) FROM CLIENTE)
ORDER BY MAIOR_COMPRA DESC
LIMIT 1;

SELECT * FROM V_COMPRAMAXCLIENTE;

