CREATE DATABASE OFICINA;
USE OFICINA;

drop table cliente;

CREATE TABLE CLIENTE (
ID_CLIENTE INT PRIMARY KEY auto_increment,
ID_CARRO INT UNIQUE,
NOME VARCHAR(30) NOT NULL,
SEXO ENUM ("M", "F") NOT NULL);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARROS
FOREIGN KEY (ID_CARRO) 
REFERENCES CARROS(ID_CARRO);

select * FROM CLIENTE;

CREATE TABLE TELEFONES_CLIENTES (
ID_TELEFONE INT primary KEY AUTO_INCREMENT ,
ID_CLIENTE INT,
TIPO ENUM("CEL", "RES", "COM") NOT NULL,
NUMERO VARCHAR(30));

ALTER TABLE TELEFONES_CLIENTES
ADD CONSTRAINT FK_TELEFONES_CLIENTES
FOREIGN KEY (ID_CLIENTE) 
REFERENCES CLIENTE(ID_CLIENTE);

select * FROM TELEFONES_CLIENTES;

CREATE TABLE CARROS (
ID_CARRO INT UNIQUE primary KEY AUTO_INCREMENT ,
ID_MARCA INT,
MODELO VARCHAR(30),
PLACA VARCHAR(15));

ALTER TABLE CARROS
ADD CONSTRAINT FK_CARROS
FOREIGN KEY (ID_MARCA) 
REFERENCES MARCA(ID_MARCA);

select * FROM CARROS;

CREATE TABLE MARCA (
ID_MARCA INT PRIMARY KEY AUTO_INCREMENT,
MARCA VARCHAR(30) UNIQUE);

select * FROM MARCA;

CREATE TABLE CARRO_COR (
ID_CARRO INT,
ID_COR INT);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO_COR
FOREIGN KEY (ID_CARRO) REFERENCES CARROS(ID_CARRO);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO_COR2
FOREIGN KEY (ID_COR) REFERENCES CORES(ID_COR);

SELECT * FROM CARRO_COR;

CREATE TABLE CORES (
ID_COR INT primary KEY auto_increment,
COR VARCHAR (40));

SELECT * FROM CORES;
